// 最新の都道府県と市区町村データ（2025年対応）
export const ADDRESS_DATA = {
    prefectures: [
        { code: '01', name: '北海道' },
        { code: '02', name: '青森県' },
        { code: '03', name: '岩手県' },
        { code: '04', name: '宮城県' },
        { code: '05', name: '秋田県' },
        { code: '06', name: '山形県' },
        { code: '07', name: '福島県' },
        { code: '08', name: '茨城県' },
        { code: '09', name: '栃木県' },
        { code: '10', name: '群馬県' },
        { code: '11', name: '埼玉県' },
        { code: '12', name: '千葉県' },
        { code: '13', name: '東京都' },
        { code: '14', name: '神奈川県' },
        { code: '15', name: '新潟県' },
        { code: '16', name: '富山県' },
        { code: '17', name: '石川県' },
        { code: '18', name: '福井県' },
        { code: '19', name: '山梨県' },
        { code: '20', name: '長野県' },
        { code: '21', name: '岐阜県' },
        { code: '22', name: '静岡県' },
        { code: '23', name: '愛知県' },
        { code: '24', name: '三重県' },
        { code: '25', name: '滋賀県' },
        { code: '26', name: '京都府' },
        { code: '27', name: '大阪府' },
        { code: '28', name: '兵庫県' },
        { code: '29', name: '奈良県' },
        { code: '30', name: '和歌山県' },
        { code: '31', name: '鳥取県' },
        { code: '32', name: '島根県' },
        { code: '33', name: '岡山県' },
        { code: '34', name: '広島県' },
        { code: '35', name: '山口県' },
        { code: '36', name: '徳島県' },
        { code: '37', name: '香川県' },
        { code: '38', name: '愛媛県' },
        { code: '39', name: '高知県' },
        { code: '40', name: '福岡県' },
        { code: '41', name: '佐賀県' },
        { code: '42', name: '長崎県' },
        { code: '43', name: '熊本県' },
        { code: '44', name: '大分県' },
        { code: '45', name: '宮崎県' },
        { code: '46', name: '鹿児島県' },
        { code: '47', name: '沖縄県' }
    ],

    cities: {
        '01': [ // 北海道
            { code: '01100', name: '札幌市' },
            { code: '01202', name: '函館市' },
            { code: '01203', name: '小樽市' },
            { code: '01204', name: '旭川市' },
            { code: '01205', name: '室蘭市' },
            { code: '01206', name: '釧路市' },
            { code: '01207', name: '帯広市' },
            { code: '01208', name: '北見市' },
            { code: '01209', name: '夕張市' },
            { code: '01210', name: '岩見沢市' },
            { code: '01211', name: '網走市' },
            { code: '01212', name: '留萌市' },
            { code: '01213', name: '苫小牧市' },
            { code: '01214', name: '稚内市' },
            { code: '01215', name: '美唄市' },
            { code: '01216', name: '芦別市' },
            { code: '01217', name: '江別市' },
            { code: '01218', name: '赤平市' },
            { code: '01219', name: '紋別市' },
            { code: '01220', name: '士別市' },
            { code: '01221', name: '名寄市' },
            { code: '01222', name: '三笠市' },
            { code: '01223', name: '根室市' },
            { code: '01224', name: '千歳市' },
            { code: '01225', name: '滝川市' },
            { code: '01226', name: '砂川市' },
            { code: '01227', name: '歌志内市' },
            { code: '01228', name: '深川市' },
            { code: '01229', name: '富良野市' },
            { code: '01230', name: '登別市' },
            { code: '01231', name: '恵庭市' },
            { code: '01233', name: '伊達市' },
            { code: '01234', name: '北広島市' },
            { code: '01235', name: '石狩市' },
            { code: '01236', name: '北斗市' }
        ],
        '13': [ // 東京都
            { code: '13101', name: '千代田区' },
            { code: '13102', name: '中央区' },
            { code: '13103', name: '港区' },
            { code: '13104', name: '新宿区' },
            { code: '13105', name: '文京区' },
            { code: '13106', name: '台東区' },
            { code: '13107', name: '墨田区' },
            { code: '13108', name: '江東区' },
            { code: '13109', name: '品川区' },
            { code: '13110', name: '目黒区' },
            { code: '13111', name: '大田区' },
            { code: '13112', name: '世田谷区' },
            { code: '13113', name: '渋谷区' },
            { code: '13114', name: '中野区' },
            { code: '13115', name: '杉並区' },
            { code: '13116', name: '豊島区' },
            { code: '13117', name: '北区' },
            { code: '13118', name: '荒川区' },
            { code: '13119', name: '板橋区' },
            { code: '13120', name: '練馬区' },
            { code: '13121', name: '足立区' },
            { code: '13122', name: '葛飾区' },
            { code: '13123', name: '江戸川区' },
            { code: '13201', name: '八王子市' },
            { code: '13202', name: '立川市' },
            { code: '13203', name: '武蔵野市' },
            { code: '13204', name: '三鷹市' },
            { code: '13205', name: '青梅市' },
            { code: '13206', name: '府中市' },
            { code: '13207', name: '昭島市' },
            { code: '13208', name: '調布市' },
            { code: '13209', name: '町田市' },
            { code: '13210', name: '小金井市' },
            { code: '13211', name: '小平市' },
            { code: '13212', name: '日野市' },
            { code: '13213', name: '東村山市' },
            { code: '13214', name: '国分寺市' },
            { code: '13215', name: '国立市' },
            { code: '13218', name: '福生市' },
            { code: '13219', name: '狛江市' },
            { code: '13220', name: '東大和市' },
            { code: '13221', name: '清瀬市' },
            { code: '13222', name: '東久留米市' },
            { code: '13223', name: '武蔵村山市' },
            { code: '13224', name: '多摩市' },
            { code: '13225', name: '稲城市' },
            { code: '13227', name: '羽村市' },
            { code: '13228', name: 'あきる野市' },
            { code: '13229', name: '西東京市' }
        ],
        '23': [ // 愛知県
            { code: '23100', name: '名古屋市' },
            { code: '23201', name: '豊橋市' },
            { code: '23202', name: '岡崎市' },
            { code: '23203', name: '一宮市' },
            { code: '23204', name: '瀬戸市' },
            { code: '23205', name: '半田市' },
            { code: '23206', name: '春日井市' },
            { code: '23207', name: '豊川市' },
            { code: '23208', name: '津島市' },
            { code: '23209', name: '碧南市' },
            { code: '23210', name: '刈谷市' },
            { code: '23211', name: '豊田市' },
            { code: '23212', name: '安城市' },
            { code: '23213', name: '西尾市' },
            { code: '23214', name: '蒲郡市' },
            { code: '23215', name: '犬山市' },
            { code: '23216', name: '常滑市' },
            { code: '23217', name: '江南市' },
            { code: '23219', name: '小牧市' },
            { code: '23220', name: '稲沢市' },
            { code: '23221', name: '新城市' },
            { code: '23222', name: '東海市' },
            { code: '23223', name: '大府市' },
            { code: '23224', name: '知多市' },
            { code: '23225', name: '知立市' },
            { code: '23226', name: '尾張旭市' },
            { code: '23227', name: '高浜市' },
            { code: '23228', name: '岩倉市' },
            { code: '23229', name: '豊明市' },
            { code: '23230', name: '日進市' },
            { code: '23231', name: '田原市' },
            { code: '23232', name: '愛西市' },
            { code: '23233', name: '清須市' },
            { code: '23234', name: '北名古屋市' },
            { code: '23235', name: '弥富市' },
            { code: '23236', name: 'みよし市' },
            { code: '23237', name: 'あま市' },
            { code: '23238', name: '長久手市' }
        ],
        '26': [ // 京都府
            { code: '26100', name: '京都市' },
            { code: '26201', name: '福知山市' },
            { code: '26202', name: '舞鶴市' },
            { code: '26203', name: '綾部市' },
            { code: '26204', name: '宇治市' },
            { code: '26205', name: '宮津市' },
            { code: '26206', name: '亀岡市' },
            { code: '26207', name: '城陽市' },
            { code: '26208', name: '向日市' },
            { code: '26209', name: '長岡京市' },
            { code: '26210', name: '八幡市' },
            { code: '26211', name: '京田辺市' },
            { code: '26212', name: '京丹後市' },
            { code: '26213', name: '南丹市' },
            { code: '26214', name: '木津川市' }
        ],
        '27': [ // 大阪府
            { code: '27100', name: '大阪市' },
            { code: '27140', name: '堺市' },
            { code: '27202', name: '岸和田市' },
            { code: '27203', name: '豊中市' },
            { code: '27204', name: '池田市' },
            { code: '27205', name: '吹田市' },
            { code: '27206', name: '泉大津市' },
            { code: '27207', name: '高槻市' },
            { code: '27208', name: '貝塚市' },
            { code: '27209', name: '守口市' },
            { code: '27210', name: '枚方市' },
            { code: '27211', name: '茨木市' },
            { code: '27212', name: '八尾市' },
            { code: '27213', name: '泉佐野市' },
            { code: '27214', name: '富田林市' },
            { code: '27215', name: '寝屋川市' },
            { code: '27216', name: '河内長野市' },
            { code: '27217', name: '松原市' },
            { code: '27218', name: '大東市' },
            { code: '27219', name: '和泉市' },
            { code: '27220', name: '箕面市' },
            { code: '27221', name: '柏原市' },
            { code: '27222', name: '羽曳野市' },
            { code: '27223', name: '門真市' },
            { code: '27224', name: '摂津市' },
            { code: '27225', name: '高石市' },
            { code: '27226', name: '藤井寺市' },
            { code: '27227', name: '東大阪市' },
            { code: '27228', name: '泉南市' },
            { code: '27229', name: '四條畷市' },
            { code: '27230', name: '交野市' },
            { code: '27231', name: '大阪狭山市' },
            { code: '27232', name: '阪南市' }
        ],
        '28': [ // 兵庫県
            { code: '28100', name: '神戸市' },
            { code: '28201', name: '姫路市' },
            { code: '28202', name: '尼崎市' },
            { code: '28203', name: '明石市' },
            { code: '28204', name: '西宮市' },
            { code: '28205', name: '洲本市' },
            { code: '28206', name: '芦屋市' },
            { code: '28207', name: '伊丹市' },
            { code: '28208', name: '相生市' },
            { code: '28209', name: '豊岡市' },
            { code: '28210', name: '加古川市' },
            { code: '28212', name: '赤穂市' },
            { code: '28213', name: '西脇市' },
            { code: '28214', name: '宝塚市' },
            { code: '28215', name: '三木市' },
            { code: '28216', name: '高砂市' },
            { code: '28217', name: '川西市' },
            { code: '28218', name: '小野市' },
            { code: '28219', name: '三田市' },
            { code: '28220', name: '加西市' },
            { code: '28221', name: '丹波篠山市' },
            { code: '28222', name: '養父市' },
            { code: '28223', name: '丹波市' },
            { code: '28224', name: '南あわじ市' },
            { code: '28225', name: '朝来市' },
            { code: '28226', name: '淡路市' },
            { code: '28227', name: '宍粟市' },
            { code: '28228', name: '加東市' },
            { code: '28229', name: 'たつの市' }
        ],
        '14': [ // 神奈川県
            { code: '14100', name: '横浜市' },
            { code: '14130', name: '川崎市' },
            { code: '14150', name: '相模原市' },
            { code: '14201', name: '横須賀市' },
            { code: '14203', name: '平塚市' },
            { code: '14204', name: '鎌倉市' },
            { code: '14205', name: '藤沢市' },
            { code: '14206', name: '小田原市' },
            { code: '14207', name: '茅ヶ崎市' },
            { code: '14208', name: '逗子市' },
            { code: '14210', name: '三浦市' },
            { code: '14211', name: '秦野市' },
            { code: '14212', name: '厚木市' },
            { code: '14213', name: '大和市' },
            { code: '14214', name: '伊勢原市' },
            { code: '14215', name: '海老名市' },
            { code: '14216', name: '座間市' },
            { code: '14217', name: '南足柄市' },
            { code: '14218', name: '綾瀬市' }
        ],
        '11': [ // 埼玉県
            { code: '11100', name: 'さいたま市' },
            { code: '11201', name: '川越市' },
            { code: '11202', name: '熊谷市' },
            { code: '11203', name: '川口市' },
            { code: '11206', name: '行田市' },
            { code: '11207', name: '秩父市' },
            { code: '11208', name: '所沢市' },
            { code: '11209', name: '飯能市' },
            { code: '11210', name: '加須市' },
            { code: '11211', name: '本庄市' },
            { code: '11212', name: '東松山市' },
            { code: '11214', name: '春日部市' },
            { code: '11215', name: '狭山市' },
            { code: '11216', name: '羽生市' },
            { code: '11217', name: '鴻巣市' },
            { code: '11218', name: '深谷市' },
            { code: '11219', name: '上尾市' },
            { code: '11221', name: '草加市' },
            { code: '11222', name: '越谷市' },
            { code: '11223', name: '蕨市' },
            { code: '11224', name: '戸田市' },
            { code: '11225', name: '入間市' },
            { code: '11227', name: '朝霞市' },
            { code: '11228', name: '志木市' },
            { code: '11229', name: '和光市' },
            { code: '11230', name: '新座市' },
            { code: '11231', name: '桶川市' },
            { code: '11232', name: '久喜市' },
            { code: '11233', name: '北本市' },
            { code: '11234', name: '八潮市' },
            { code: '11235', name: '富士見市' },
            { code: '11237', name: '三郷市' },
            { code: '11238', name: '蓮田市' },
            { code: '11239', name: '坂戸市' },
            { code: '11240', name: '幸手市' },
            { code: '11241', name: '鶴ヶ島市' },
            { code: '11242', name: '日高市' },
            { code: '11243', name: '吉川市' },
            { code: '11245', name: 'ふじみ野市' },
            { code: '11246', name: '白岡市' }
        ],
        '12': [ // 千葉県
            { code: '12100', name: '千葉市' },
            { code: '12202', name: '銚子市' },
            { code: '12203', name: '市川市' },
            { code: '12204', name: '船橋市' },
            { code: '12205', name: '館山市' },
            { code: '12206', name: '木更津市' },
            { code: '12207', name: '松戸市' },
            { code: '12208', name: '野田市' },
            { code: '12210', name: '茂原市' },
            { code: '12211', name: '成田市' },
            { code: '12212', name: '佐倉市' },
            { code: '12213', name: '東金市' },
            { code: '12215', name: '旭市' },
            { code: '12216', name: '習志野市' },
            { code: '12217', name: '柏市' },
            { code: '12218', name: '勝浦市' },
            { code: '12219', name: '市原市' },
            { code: '12220', name: '流山市' },
            { code: '12221', name: '八千代市' },
            { code: '12222', name: '我孫子市' },
            { code: '12223', name: '鴨川市' },
            { code: '12224', name: '鎌ケ谷市' },
            { code: '12225', name: '君津市' },
            { code: '12226', name: '富津市' },
            { code: '12227', name: '浦安市' },
            { code: '12228', name: '四街道市' },
            { code: '12229', name: '袖ケ浦市' },
            { code: '12230', name: '八街市' },
            { code: '12231', name: '印西市' },
            { code: '12232', name: '白井市' },
            { code: '12233', name: '富里市' },
            { code: '12234', name: '南房総市' },
            { code: '12235', name: '匝瑳市' },
            { code: '12236', name: '香取市' },
            { code: '12237', name: '山武市' },
            { code: '12238', name: 'いすみ市' },
            { code: '12239', name: '大網白里市' }
        ],
        '40': [ // 福岡県
            { code: '40100', name: '北九州市' },
            { code: '40130', name: '福岡市' },
            { code: '40202', name: '大牟田市' },
            { code: '40203', name: '久留米市' },
            { code: '40204', name: '直方市' },
            { code: '40205', name: '飯塚市' },
            { code: '40206', name: '田川市' },
            { code: '40207', name: '柳川市' },
            { code: '40209', name: '八女市' },
            { code: '40210', name: '筑後市' },
            { code: '40211', name: '大川市' },
            { code: '40212', name: '行橋市' },
            { code: '40213', name: '豊前市' },
            { code: '40214', name: '中間市' },
            { code: '40215', name: '小郡市' },
            { code: '40216', name: '筑紫野市' },
            { code: '40217', name: '春日市' },
            { code: '40218', name: '大野城市' },
            { code: '40219', name: '宗像市' },
            { code: '40220', name: '太宰府市' },
            { code: '40223', name: '古賀市' },
            { code: '40224', name: '福津市' },
            { code: '40225', name: 'うきは市' },
            { code: '40226', name: '宮若市' },
            { code: '40227', name: '嘉麻市' },
            { code: '40228', name: '朝倉市' },
            { code: '40229', name: 'みやま市' },
            { code: '40230', name: '糸島市' },
            { code: '40231', name: '那珂川市' }
        ]
    }
};

// 都道府県の選択肢を取得
export const getPrefectureOptions = () => {
    return ['', ...ADDRESS_DATA.prefectures.map(pref => pref.name)];
};

// 指定された都道府県に対応する市区町村の選択肢を取得
export const getCityOptions = (prefectureName) => {
    if (!prefectureName) {
        return [''];
    }

    const prefecture = ADDRESS_DATA.prefectures.find(pref => pref.name === prefectureName);
    if (!prefecture) {
        return [''];
    }

    const cities = ADDRESS_DATA.cities[prefecture.code] || [];
    return ['', ...cities.map(city => city.name)];
};

// 都道府県コードから都道府県名を取得
export const getPrefectureName = (code) => {
    const prefecture = ADDRESS_DATA.prefectures.find(pref => pref.code === code);
    return prefecture ? prefecture.name : '';
};

// 市区町村コードから市区町村名を取得
export const getCityName = (code) => {
    for (const prefCode in ADDRESS_DATA.cities) {
        const city = ADDRESS_DATA.cities[prefCode].find(city => city.code === code);
        if (city) {
            return city.name;
        }
    }
    return '';
};
